### ISSUE TITLE
What is used by an existing network with added modules

### ISSUE THREAD

**Issue by shiyuan680** [LeonHLJ/FAC-Net#2]
What is the moment localization network used to achieve the accuracy in this paper

**Comment by LeonHLJ** [comment]
> What is the moment localization network used to achieve the accuracy in this paper

Sorry, maybe you can describe your problem in more detail. Do you mean which proposal generation network we used? Actually, most WSTAL methods do not follow the two-stage pipeline used in fully supervised methods that first generate temporal proposals, WSTAL methods are usually in a one-stage fashion that generates the classification score for each frame, and then thresholds the frame-wise classification scores to obtain action instances.

**Comment by shiyuan680** [comment]
Thank you for your reply. I mean, what existing wstal method do you recommend to verify the function of this module.

**Comment by LeonHLJ** [comment]
> Thank you for your reply. I mean, what existing wstal method do you recommend to verify the function of this module.

You can plug our module into STPN, W-TALC, Background Modeling Network, BaS-Net, etc.
