### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by JosephKKim** [LeonHLJ/FAC-Net#6]
Hello, Thanks for making your interesting work open to the public, 
I am a student recently studying on WS-TAL tasks. 
What I want to ask is about "how to visualize results from network so that it can be the one shown in the paper."
For example, like the ones in the Figure 1 and 5 in your paper.

Thanks, Joseph

**Comment by LeonHLJ** [comment]
> Hello, Thanks for making your interesting work open to the public, I am a student recently studying on WS-TAL tasks. What I want to ask is about "how to visualize results from network so that it can be the one shown in the paper." For example, like the ones in the Figure 1 and 5 in your paper.
> 
> Thanks, Joseph

Thanks for your interest in our work. We utilize the matplotlib package to plot the scores and ground truth for each video and output the figures in PDF format. Then you can use some PDF software to merge the visualization results of several videos and paste some video frames on the figure.  Maybe there are some easier ways to achieve it, but I think this process is not very hard to execute. Hope it can help you.

**Comment by JosephKKim** [comment]
Thank you so much for the detailed reply.
I am planning for the project on this topic and your reply helped me a lot!
