### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by zhou-ning** [LeonHLJ/FAC-Net#7]
你好，我是一个学生，最近在复现您的论文，但是我使用您的代码，训练了50000轮后，mAP在任何iou下都降为了0，请问您遇到这样的情况了吗

**Comment by LeonHLJ** [comment]
> 
我在训练中没有遇到你所提到的问题，如果你没有修改原始代码，我猜想可能有以下原因：
(1) 模型在训练过程中遇到了数值不稳定的情况，通常是由于除以接近于0的值，可以尝试增加loss的分母项的1e-8，使数值尽量保存稳定。
(2) 由于模型较小，受初始化的影响较大，可以尝试修改torch seed来解决

**Comment by zhou-ning** [comment]
好的，谢谢
