### ISSUE TITLE
ActivityNet V1.3数据集的缺失问题

### ISSUE THREAD

**Issue by mymuli** [LeonHLJ/FAC-Net#9]
您好！
我在您的utils/video_dataloader.py文件里面，有看到-I3D-JOINTFeatures.npy文件：

https://github.com/LeonHLJ/FAC-Net/blob/c0108860ecb679a14ef1c3722581b20434271433/utils/video_dataloader.py#L14
我想问一下，您是否可以提供一下ActivityNet1.3-I3D-JOINTFeatures.npy文件和ActivityNet1.3-Annotation文件夹里面的文件呢？

或者我如何制作一个总的ActivityNet1.3-I3D-JOINTFeatures.np文件以及ActivityNet1.3-Annotation文件夹里面的classlist.npy、labels_all.npy等文件呢？

冒昧打扰，十分抱歉！

**Comment by LeonHLJ** [comment]
> 您好！ 我在您的utils/video_dataloader.py文件里面，有看到-I3D-JOINTFeatures.npy文件：
> 
> https://github.com/LeonHLJ/FAC-Net/blob/c0108860ecb679a14ef1c3722581b20434271433/utils/video_dataloader.py#L14
> 
> 
> 我想问一下，您是否可以提供一下ActivityNet1.3-I3D-JOINTFeatures.npy文件和ActivityNet1.3-Annotation文件夹里面的文件呢？
> 或者我如何制作一个总的ActivityNet1.3-I3D-JOINTFeatures.np文件以及ActivityNet1.3-Annotation文件夹里面的classlist.npy、labels_all.npy等文件呢？
> 
> 冒昧打扰，十分抱歉！

Thank you for your interest in our research. For detailed training pipeline, including the extracted features and required files, and testing strategies applicable to ActivityNet, you can refer to [ACMNet](https://github.com/ispc-lab/ACM-Net).

**Comment by mymuli** [comment]
非常感谢您的回复！

我想问一下，您的FAC-Net模型在ActivityNet1.3数据集的实验， 是利用 ACM-Net模型作者 生成的ActivityNet1.3数据集特征和它的数据读取框架吗？

**Comment by LeonHLJ** [comment]
> 非常感谢您的回复！
> 
> 我想问一下，您的FAC-Net模型在ActivityNet1.3数据集的实验， 是利用 ACM-Net模型作者 生成的ActivityNet1.3数据集特征和它的数据读取框架吗？

Yes.  You can try the training and evaluation code from ACM-Net for AcNet 1.3. However, you'll need to make some modifications to the evaluation pipeline, primarily in terms of adjusting certain hyperparameters and post-processings.

**Comment by mymuli** [comment]
好的，非常感谢您！
